### ISSUE TITLE
Equality Check vs. Bit Mask When value_type == 0x07?

### ISSUE THREAD

**Issue by mbartle** [ydkhatri/spotlight_parser#2]
https://github.com/ydkhatri/spotlight_parser/blob/e02212e944e4181009e10a4ec54c2d4bdb29c134/spotlight_parser.py#L250

Looking at [Apple's documentation](https://developer.apple.com/library/archive/documentation/Carbon/Conceptual/MDImporters/Concepts/SchemaRef.html#//apple_ref/doc/uid/TP40001832-221481), there are three boolean values corresponding to each spotlight property, in addition to the property's type and name, `multivalued`, `uniqued`, and `nosearch`. It seems that, since `prop_type & 0x02 == 0x02` when we want an array for most `value_type`s, `multivalued` is represented by the second LSB. It seems odd to make an equality check on 0x02 in this case, then. Why not a bit mask on 0x02 (or on 0x42) instead?

**Comment by ydkhatri** [comment]
This one (value_type==7 && proptype==0x42) is a bit of a mystery to me. It is probably also following the same convention as others (regarding bit 2), however I do not have enough data to test this. Only one of my test images exhibits these properties and the parsing contained there (lines 252-260) are based on that one sample.

If you have samples that demonstrate this, please test it and fix the code.

**Comment by mbartle** [comment]
I also don't have enough data to test this, just wanted to bring up bit 2.
