### ISSUE TITLE
Should be ReadDouble

### ISSUE THREAD

**Issue by mbartle** [ydkhatri/spotlight_parser#3]
https://github.com/ydkhatri/spotlight_parser/blob/e02212e944e4181009e10a4ec54c2d4bdb29c134/spotlight_parser.py#L273

I think this line should have `self.ReadDouble()` instead of `self.ReadDate()`.

**Comment by ydkhatri** [comment]
I've only seen dates in that value_type 0xA, and hence the call to read and convert to date. `self.ReadDate()` does call `self.ReadDouble()`
Are you seeing a number stored there instead of a date? Or am I misunderstanding your query?

**Comment by mbartle** [comment]
I thought this was a typo, because when `value_type == 0x0A && prop_type & 2 != 2`, you read a double, and because here you're assigning to a variable called `doubles`. Also, the only example in my own system's `store.db` to hit this case (`value_type == 0x0A && prop_type & 2 == 2`) was an array denoting four points of a rectangle.

**Comment by ydkhatri** [comment]
It may very well be a typo! Will run some tests and revert back.

**Comment by ydkhatri** [comment]
OK, I verified this is a typo, and it has been fixed now. Thanks for submitting this bug.
