### ISSUE TITLE
No Bitmask For String value_type

### ISSUE THREAD

**Issue by mbartle** [ydkhatri/spotlight_parser#4]
https://github.com/ydkhatri/spotlight_parser/blob/e02212e944e4181009e10a4ec54c2d4bdb29c134/spotlight_parser.py#L278

Why not keep the `& 2 == 2` conditional, here? Even if you're converting single-item lists of strings to strings below, wouldn't we like to have an empty string, rather than an empty list, when the value is a single null byte?

**Comment by ydkhatri** [comment]
Yes, that would be more technically correct, although no practical difference in output. Feel free to make a pull request.
