### ISSUE TITLE
Metadata Block Check Should Use Equality

### ISSUE THREAD

**Issue by mbartle** [ydkhatri/spotlight_parser#5]
https://github.com/ydkhatri/spotlight_parser/blob/e02212e944e4181009e10a4ec54c2d4bdb29c134/spotlight_parser.py#L570

This does not seem like the right check. If the last byte of BlockType.METADATA is 00001001, and we're checking `block_type & BlockType.METADATA`, then we'll accept any block that happens to have its 0th and 3rd bits set. Should this be `blocktype << 24 != BlockType.METADATA << 24`?

**Comment by ydkhatri** [comment]
You are right on this. It should be `compressed_block.block_type & 0xFF != BlockType.METADATA`

**Comment by ydkhatri** [comment]
Code has been updated to fix this.
